### PR TITLE
CocoaPods support

### PR DESCRIPTION
**Pull request by marcelofabri**
Adding a podspec and making some stuff public.

### CODE REVIEW

**Comment by ararog** [comment]
+1

**Comment by Isuru-Nanayakkara** [comment]
Hi @marcelofabri, thank you for adding CocoaPods support. Quick question 'cause I'm not entirely familiar with the pod authoring process. If someone adds Reachability through CocoaPods, does it get added as a framework or as a static library?

**Comment by Isuru-Nanayakkara** [comment]
@ararog @marcelofabri Thank you both. I merged it. I also tested it with a test project and it works fine.

Do I have to do anything else? For example for the library to be indexed in the cocoapods site?

**Comment by ararog** [comment]
Please refer to http://cocoapods.org/#create_a_pod for more details.

**Comment by marcelofabri** [comment]
Yeah, you'd need to add a tag and submit to CocoaPods. However, I'd only do that after 0.36 is officially released.

**Comment by Isuru-Nanayakkara** [comment]
Got it. Thanks.

**Comment by Isuru-Nanayakkara** [comment]
Hello again,

I made some changes to the project. I renamed the repo, removed the old Xcode sample project and pushed a new one. I also modified the .podspec file to reflect the changes I made.

But I tried adding the library through CocoaPods now, but it doesn't seem to be working properly.
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'IJReachability', :git => 'https://github.com/Isuru-Nanayakkara/IJReachability.git'
```

When I run `pod install`, the following line gets outputted in the Terminal.
**fatal: Not a git repository (or any of the parent directories): .git**

However the pod installation succeeds and the .workspace file is created. I open that, `import IJReachability` on a file (compiles fine) but if I try to call a method (for example `isConnectedToNetwork()`), I get the following error.
**'IJReachability.Type' does not have a member named 'isConnectedToNetwork'**

I've been trying to resolve this but no luck so far. Do you guys have any idea what might have gone wrong?

**Pull request merged**
